version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://it22157232:1234@task.pgt3jhz.mongodb.net/?retryWrites=true&w=majority&appName=task
      - JWT_SECRET=SecurityKeyJWT
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
